"""initdb

Revision ID: 44182122a585
Revises: 
Create Date: 2022-01-28 21:03:41.006730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44182122a585'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=36), nullable=True),
    sa.Column('netconf_host', sa.String(length=36), nullable=True),
    sa.Column('netconf_port', sa.Integer(), nullable=True),
    sa.Column('netconf_username', sa.String(length=36), nullable=True),
    sa.Column('netconf_password', sa.String(length=36), nullable=True),
    sa.Column('tf_api_server_host', sa.String(length=36), nullable=False),
    sa.Column('tf_api_server_port', sa.Integer(), nullable=False),
    sa.Column('tf_username', sa.String(length=36), nullable=False),
    sa.Column('tf_password', sa.String(length=36), nullable=False),
    sa.Column('os_auth_url', sa.String(length=36), nullable=True),
    sa.Column('os_region', sa.String(length=36), nullable=True),
    sa.Column('os_project_domain_name', sa.String(length=36), nullable=True),
    sa.Column('os_user_domain_name', sa.String(length=36), nullable=True),
    sa.Column('os_project_name', sa.String(length=36), nullable=False),
    sa.Column('os_username', sa.String(length=36), nullable=True),
    sa.Column('os_password', sa.String(length=36), nullable=True),
    sa.Column('state', sa.Enum('ACTIVE', 'INACTIVE'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('wan_nodes',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=36), nullable=True),
    sa.Column('vendor', sa.Enum('huawei'), nullable=False),
    sa.Column('configure_mode', sa.Enum('sshcli', 'netconf'), nullable=False),
    sa.Column('ssh_host', sa.String(length=36), nullable=True),
    sa.Column('ssh_port', sa.Integer(), nullable=True),
    sa.Column('ssh_username', sa.String(length=36), nullable=True),
    sa.Column('ssh_password', sa.String(length=36), nullable=True),
    sa.Column('privilege_password', sa.String(length=36), nullable=True),
    sa.Column('netconf_host', sa.String(length=36), nullable=True),
    sa.Column('netconf_port', sa.Integer(), nullable=True),
    sa.Column('netconf_username', sa.String(length=36), nullable=True),
    sa.Column('netconf_password', sa.String(length=36), nullable=True),
    sa.Column('as_number', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('ACTIVE', 'INACTIVE'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('l3_vpn_srv6_slicings',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=36), nullable=True),
    sa.Column('east_site_uuid', sa.String(length=36), nullable=False),
    sa.Column('east_site_subnet_cidr', sa.String(length=36), nullable=False),
    sa.Column('east_site_vn_uuid', sa.String(length=36), nullable=True),
    sa.Column('west_site_uuid', sa.String(length=36), nullable=False),
    sa.Column('west_site_subnet_cidr', sa.String(length=36), nullable=False),
    sa.Column('west_site_vn_uuid', sa.String(length=36), nullable=True),
    sa.Column('routing_type', sa.Enum('be', 'te'), nullable=False),
    sa.Column('ingress_node', sa.String(length=36), nullable=True),
    sa.Column('egress_node', sa.String(length=36), nullable=True),
    sa.Column('route_target', sa.String(length=36), nullable=True),
    sa.Column('is_keepalive', sa.Boolean(), nullable=True),
    sa.Column('state', sa.Enum('ACTIVE', 'INACTIVE'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('l2_evpn_dcis',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=36), nullable=True),
    sa.Column('east_site_uuid', sa.String(length=36), nullable=False),
    sa.Column('west_site_uuid', sa.String(length=36), nullable=False),
    sa.Column('subnet_cidr', sa.String(length=36), nullable=False),
    sa.Column('east_site_subnet_allocation_pool', sa.String(length=36), nullable=False),
    sa.Column('west_site_subnet_allocation_pool', sa.String(length=36), nullable=False),
    sa.Column('vn_route_target', sa.String(length=36), nullable=False),
    sa.Column('inter_vlan_id', sa.Integer(), nullable=False),
    sa.Column('dci_vni', sa.Integer(), nullable=False),
    sa.Column('east_site_vn_uuid', sa.String(length=36), nullable=True),
    sa.Column('west_site_vn_uuid', sa.String(length=36), nullable=True),
    sa.Column('state', sa.Enum('ACTIVE', 'INACTIVE'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('l3_evpn_dcis',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=36), nullable=True),
    sa.Column('east_site_uuid', sa.String(length=36), nullable=False),
    sa.Column('east_site_subnet_cidr', sa.String(length=36), nullable=False),
    sa.Column('east_site_vn_uuid', sa.String(length=36), nullable=True),
    sa.Column('west_site_uuid', sa.String(length=36), nullable=True),
    sa.Column('west_site_subnet_cidr', sa.String(length=36), nullable=False),
    sa.Column('west_site_vn_uuid', sa.String(length=36), nullable=True),
    sa.Column('state', sa.Enum('ACTIVE', 'INACTIVE'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('l3_evpn_dcis')
    op.drop_table('l2_evpn_dcis')
    op.drop_table('l3_vpn_srv6_slicings')
    op.drop_table('wan_nodes')
    op.drop_table('sites')
    # ### end Alembic commands ###
