"""initdb

Revision ID: dbe4a789381f
Revises: 
Create Date: 2021-11-25 10:05:21.946144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbe4a789381f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=36), nullable=True),
    sa.Column('netconf_host', sa.String(length=36), nullable=False),
    sa.Column('netconf_username', sa.String(length=36), nullable=False),
    sa.Column('netconf_password', sa.String(length=36), nullable=False),
    sa.Column('state', sa.Enum('active', 'inactive'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sites')
    # ### end Alembic commands ###
