"""initdb

Revision ID: e68fb44ce0e2
Revises: 
Create Date: 2021-11-29 09:15:46.200825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e68fb44ce0e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=36), nullable=True),
    sa.Column('netconf_host', sa.String(length=36), nullable=False),
    sa.Column('netconf_port', sa.Integer(), nullable=True),
    sa.Column('netconf_username', sa.String(length=36), nullable=False),
    sa.Column('netconf_password', sa.String(length=36), nullable=False),
    sa.Column('tf_api_server_host', sa.String(length=36), nullable=False),
    sa.Column('tf_api_server_port', sa.Integer(), nullable=True),
    sa.Column('tf_username', sa.String(length=36), nullable=False),
    sa.Column('tf_password', sa.String(length=36), nullable=False),
    sa.Column('tf_project', sa.String(length=36), nullable=True),
    sa.Column('state', sa.Enum('active', 'inactive'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('l2_evpn_dcis',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=36), nullable=True),
    sa.Column('east_site_uuid', sa.String(length=36), nullable=False),
    sa.Column('west_site_uuid', sa.String(length=36), nullable=False),
    sa.Column('subnet_cidr', sa.String(length=36), nullable=False),
    sa.Column('east_site_subnet_allocation_pool', sa.String(length=36), nullable=False),
    sa.Column('west_site_subnet_allocation_pool', sa.String(length=36), nullable=False),
    sa.Column('vlan_id', sa.Integer(), nullable=False),
    sa.Column('route_target', sa.String(length=36), nullable=False),
    sa.Column('state', sa.Enum('active', 'inactive'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('l3_evpn_dcis',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=36), nullable=True),
    sa.Column('east_site_uuid', sa.String(length=36), nullable=False),
    sa.Column('west_site_uuid', sa.String(length=36), nullable=False),
    sa.Column('east_site_subnet_cidr', sa.String(length=36), nullable=False),
    sa.Column('west_site_subnet_cidr', sa.String(length=36), nullable=False),
    sa.Column('state', sa.Enum('active', 'inactive'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('l3_evpn_dcis')
    op.drop_table('l2_evpn_dcis')
    op.drop_table('sites')
    # ### end Alembic commands ###
